name: build-and-deploy
on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci --no-audit --no-fund     # include dev
      - run: npm run build                    # needs @tailwindcss/vite
      - uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./build

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      # Install only runtime deps on the server
      - run: npm ci --omit=dev --no-audit --no-fund

      - name: Restart app with PM2
        run: |
          pm2 delete nnp || true
          pm2 start ./build/server/index.js --name nnp
          pm2 save
