name: Deploy to self-hosted (prod)

on:
  push:
    branches: [ prod ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DEPLOY_DIR: /opt/nnp-web   # must already exist and be owned by the runner user
      PORT: 3000
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure rsync present (no sudo; optional)
        run: |
          if ! command -v rsync >/dev/null; then
            echo "rsync not found; please install it on the runner once (outside CI)."
            exit 1
          fi

      - name: Install deps (for build)
        run: npm ci

      - name: Build (SSR)
        run: npm run build

      # ---- Deploy to $DEPLOY_DIR (must already exist; we do NOT create it) ----
      - name: Stage deploy
        run: |
          # sync build output
          rsync -a --delete build/ "$DEPLOY_DIR/build/"
          # sync manifests needed for runtime npm ci
          rsync -a package.json package-lock.json "$DEPLOY_DIR/"

      - name: Install runtime deps (prod only)
        working-directory: ${{ env.DEPLOY_DIR }}
        run: npm ci --omit=dev

      # ---- PM2 section (no sudo) ----
      - name: Ensure PM2 installed
        run: |
          if ! command -v pm2 >/dev/null; then
            npm i -g pm2
          fi
          pm2 -v

      - name: Restart app with PM2
        working-directory: ${{ env.DEPLOY_DIR }}
        run: |
          pm2 delete nnp-web || true
          pm2 start "npx --yes react-router-serve ./build/server/index.js --port=${PORT}" \
            --name nnp-web --update-env
          pm2 save
